backend:
  database:
    client: pg
    connection:
      host: ${DB_HOST}
      port: 5432
      user: ${user}
      password: ${password}
catalog:
  providers:
    github:
      catalogInfo:
        filters:
          branch: main
          repository: ".*"
      templates:
        filters:
          branch: main
          repository: ".*"
