---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
spec:
  id: ${{ values.name }}
  compositionSelector:
    matchLabels:
      provider: ${{ values.provider }}
  parameters:
    version: ${{ values.version }}
    nodeSize: ${{ values.nodeSize }}
    minNodeCount: ${{ values.minNodeCount }}
    namespaces:
      - dev
      - production
    usage:
      enabled: true
    apps:
      crossplane:
        enabled: true
      argocd:
        enabled: true
        host: acme.com
        repoURL: https://github.com/vfarcic/SOMETHING
        destinationNamespace: argo-cd
        sourcePath: "."
      openfunction:
        enabled: true
      dapr:
        enabled: true
      traefik:
        enabled: true
