name: ci
run-name: ci
on:
  push:
    branches:
      - main
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    env:
      TAG: 0.0.${{ github.run_number }}
      GITHUB_USER: vfarcic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: xxx
        run: env
      # - name: Install Devbox
      #   uses: jetpack-io/devbox-install-action@v0.11.0
      #   with:
      #     enable-cache: true
      #     project-path: .github/workflows
      # - name: Plugins
      #   run: devbox run plugins
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Login to ghcr
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: vfarcic
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      # - name: Build and Push
      #   run: devbox run build

      # - name: Build and push
      #   run: |
      #     earthly --push \
      #       --secret cosignpassword="$COSIGN_PASSWORD" \
      #       --secret cosignkey="$COSIGN_PRIVATE_KEY" \
      #       --secret password="$REGISTRY_PASSWORD" \
      #       +all --tag $TAG
      #   env:
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      #     REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      # - name: Commit changes
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Release ${{ env.TAG }} [skip ci]"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
